// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: bridge.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Mpsim {

  /// <summary>Holder for reflection information generated from bridge.proto</summary>
  public static partial class BridgeReflection {

    #region Descriptor
    /// <summary>File descriptor for bridge.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BridgeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxicmlkZ2UucHJvdG8SBW1wc2ltGg5yZWFkX2FjYy5wcm90bxoPcmVhZF9n",
            "eXJvLnByb3RvGhF3cml0ZV9tb3Rvci5wcm90byKoAQoHUmVxdWVzdBIpCghy",
            "ZWFkX2FjYxgCIAEoCzIVLm1wc2ltLlJlcXVlc3RSZWFkQWNjSAASKwoJcmVh",
            "ZF9neXJvGAMgASgLMhYubXBzaW0uUmVxdWVzdFJlYWRHeXJvSAASLwoLd3Jp",
            "dGVfbW90b3IYBCABKAsyGC5tcHNpbS5SZXF1ZXN0V3JpdGVNb3RvckgAQg4K",
            "DHJlcXVlc3RfdHlwZUoECAEQAiK4AQoIUmVzcG9uc2USDwoHc3VjY2VzcxgB",
            "IAEoCBIqCghyZWFkX2FjYxgCIAEoCzIWLm1wc2ltLlJlc3BvbnNlUmVhZEFj",
            "Y0gAEiwKCXJlYWRfZ3lybxgDIAEoCzIXLm1wc2ltLlJlc3BvbnNlUmVhZEd5",
            "cm9IABIwCgt3cml0ZV9tb3RvchgEIAEoCzIZLm1wc2ltLlJlc3BvbnNlV3Jp",
            "dGVNb3RvckgAQg8KDXJlc3BvbnNlX3R5cGViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Mpsim.ReadAccReflection.Descriptor, global::Mpsim.ReadGyroReflection.Descriptor, global::Mpsim.WriteMotorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Mpsim.Request), global::Mpsim.Request.Parser, new[]{ "ReadAcc", "ReadGyro", "WriteMotor" }, new[]{ "RequestType" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Mpsim.Response), global::Mpsim.Response.Parser, new[]{ "Success", "ReadAcc", "ReadGyro", "WriteMotor" }, new[]{ "ResponseType" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Request : pb::IMessage<Request>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Request> _parser = new pb::MessageParser<Request>(() => new Request());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Request> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mpsim.BridgeReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request(Request other) : this() {
      switch (other.RequestTypeCase) {
        case RequestTypeOneofCase.ReadAcc:
          ReadAcc = other.ReadAcc.Clone();
          break;
        case RequestTypeOneofCase.ReadGyro:
          ReadGyro = other.ReadGyro.Clone();
          break;
        case RequestTypeOneofCase.WriteMotor:
          WriteMotor = other.WriteMotor.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Request Clone() {
      return new Request(this);
    }

    /// <summary>Field number for the "read_acc" field.</summary>
    public const int ReadAccFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mpsim.RequestReadAcc ReadAcc {
      get { return requestTypeCase_ == RequestTypeOneofCase.ReadAcc ? (global::Mpsim.RequestReadAcc) requestType_ : null; }
      set {
        requestType_ = value;
        requestTypeCase_ = value == null ? RequestTypeOneofCase.None : RequestTypeOneofCase.ReadAcc;
      }
    }

    /// <summary>Field number for the "read_gyro" field.</summary>
    public const int ReadGyroFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mpsim.RequestReadGyro ReadGyro {
      get { return requestTypeCase_ == RequestTypeOneofCase.ReadGyro ? (global::Mpsim.RequestReadGyro) requestType_ : null; }
      set {
        requestType_ = value;
        requestTypeCase_ = value == null ? RequestTypeOneofCase.None : RequestTypeOneofCase.ReadGyro;
      }
    }

    /// <summary>Field number for the "write_motor" field.</summary>
    public const int WriteMotorFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mpsim.RequestWriteMotor WriteMotor {
      get { return requestTypeCase_ == RequestTypeOneofCase.WriteMotor ? (global::Mpsim.RequestWriteMotor) requestType_ : null; }
      set {
        requestType_ = value;
        requestTypeCase_ = value == null ? RequestTypeOneofCase.None : RequestTypeOneofCase.WriteMotor;
      }
    }

    private object requestType_;
    /// <summary>Enum of possible cases for the "request_type" oneof.</summary>
    public enum RequestTypeOneofCase {
      None = 0,
      ReadAcc = 2,
      ReadGyro = 3,
      WriteMotor = 4,
    }
    private RequestTypeOneofCase requestTypeCase_ = RequestTypeOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public RequestTypeOneofCase RequestTypeCase {
      get { return requestTypeCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearRequestType() {
      requestTypeCase_ = RequestTypeOneofCase.None;
      requestType_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Request);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Request other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ReadAcc, other.ReadAcc)) return false;
      if (!object.Equals(ReadGyro, other.ReadGyro)) return false;
      if (!object.Equals(WriteMotor, other.WriteMotor)) return false;
      if (RequestTypeCase != other.RequestTypeCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (requestTypeCase_ == RequestTypeOneofCase.ReadAcc) hash ^= ReadAcc.GetHashCode();
      if (requestTypeCase_ == RequestTypeOneofCase.ReadGyro) hash ^= ReadGyro.GetHashCode();
      if (requestTypeCase_ == RequestTypeOneofCase.WriteMotor) hash ^= WriteMotor.GetHashCode();
      hash ^= (int) requestTypeCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (requestTypeCase_ == RequestTypeOneofCase.ReadAcc) {
        output.WriteRawTag(18);
        output.WriteMessage(ReadAcc);
      }
      if (requestTypeCase_ == RequestTypeOneofCase.ReadGyro) {
        output.WriteRawTag(26);
        output.WriteMessage(ReadGyro);
      }
      if (requestTypeCase_ == RequestTypeOneofCase.WriteMotor) {
        output.WriteRawTag(34);
        output.WriteMessage(WriteMotor);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (requestTypeCase_ == RequestTypeOneofCase.ReadAcc) {
        output.WriteRawTag(18);
        output.WriteMessage(ReadAcc);
      }
      if (requestTypeCase_ == RequestTypeOneofCase.ReadGyro) {
        output.WriteRawTag(26);
        output.WriteMessage(ReadGyro);
      }
      if (requestTypeCase_ == RequestTypeOneofCase.WriteMotor) {
        output.WriteRawTag(34);
        output.WriteMessage(WriteMotor);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (requestTypeCase_ == RequestTypeOneofCase.ReadAcc) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ReadAcc);
      }
      if (requestTypeCase_ == RequestTypeOneofCase.ReadGyro) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ReadGyro);
      }
      if (requestTypeCase_ == RequestTypeOneofCase.WriteMotor) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(WriteMotor);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Request other) {
      if (other == null) {
        return;
      }
      switch (other.RequestTypeCase) {
        case RequestTypeOneofCase.ReadAcc:
          if (ReadAcc == null) {
            ReadAcc = new global::Mpsim.RequestReadAcc();
          }
          ReadAcc.MergeFrom(other.ReadAcc);
          break;
        case RequestTypeOneofCase.ReadGyro:
          if (ReadGyro == null) {
            ReadGyro = new global::Mpsim.RequestReadGyro();
          }
          ReadGyro.MergeFrom(other.ReadGyro);
          break;
        case RequestTypeOneofCase.WriteMotor:
          if (WriteMotor == null) {
            WriteMotor = new global::Mpsim.RequestWriteMotor();
          }
          WriteMotor.MergeFrom(other.WriteMotor);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            global::Mpsim.RequestReadAcc subBuilder = new global::Mpsim.RequestReadAcc();
            if (requestTypeCase_ == RequestTypeOneofCase.ReadAcc) {
              subBuilder.MergeFrom(ReadAcc);
            }
            input.ReadMessage(subBuilder);
            ReadAcc = subBuilder;
            break;
          }
          case 26: {
            global::Mpsim.RequestReadGyro subBuilder = new global::Mpsim.RequestReadGyro();
            if (requestTypeCase_ == RequestTypeOneofCase.ReadGyro) {
              subBuilder.MergeFrom(ReadGyro);
            }
            input.ReadMessage(subBuilder);
            ReadGyro = subBuilder;
            break;
          }
          case 34: {
            global::Mpsim.RequestWriteMotor subBuilder = new global::Mpsim.RequestWriteMotor();
            if (requestTypeCase_ == RequestTypeOneofCase.WriteMotor) {
              subBuilder.MergeFrom(WriteMotor);
            }
            input.ReadMessage(subBuilder);
            WriteMotor = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18: {
            global::Mpsim.RequestReadAcc subBuilder = new global::Mpsim.RequestReadAcc();
            if (requestTypeCase_ == RequestTypeOneofCase.ReadAcc) {
              subBuilder.MergeFrom(ReadAcc);
            }
            input.ReadMessage(subBuilder);
            ReadAcc = subBuilder;
            break;
          }
          case 26: {
            global::Mpsim.RequestReadGyro subBuilder = new global::Mpsim.RequestReadGyro();
            if (requestTypeCase_ == RequestTypeOneofCase.ReadGyro) {
              subBuilder.MergeFrom(ReadGyro);
            }
            input.ReadMessage(subBuilder);
            ReadGyro = subBuilder;
            break;
          }
          case 34: {
            global::Mpsim.RequestWriteMotor subBuilder = new global::Mpsim.RequestWriteMotor();
            if (requestTypeCase_ == RequestTypeOneofCase.WriteMotor) {
              subBuilder.MergeFrom(WriteMotor);
            }
            input.ReadMessage(subBuilder);
            WriteMotor = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Response : pb::IMessage<Response>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Response> _parser = new pb::MessageParser<Response>(() => new Response());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Response> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Mpsim.BridgeReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response(Response other) : this() {
      success_ = other.success_;
      switch (other.ResponseTypeCase) {
        case ResponseTypeOneofCase.ReadAcc:
          ReadAcc = other.ReadAcc.Clone();
          break;
        case ResponseTypeOneofCase.ReadGyro:
          ReadGyro = other.ReadGyro.Clone();
          break;
        case ResponseTypeOneofCase.WriteMotor:
          WriteMotor = other.WriteMotor.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Response Clone() {
      return new Response(this);
    }

    /// <summary>Field number for the "success" field.</summary>
    public const int SuccessFieldNumber = 1;
    private bool success_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Success {
      get { return success_; }
      set {
        success_ = value;
      }
    }

    /// <summary>Field number for the "read_acc" field.</summary>
    public const int ReadAccFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mpsim.ResponseReadAcc ReadAcc {
      get { return responseTypeCase_ == ResponseTypeOneofCase.ReadAcc ? (global::Mpsim.ResponseReadAcc) responseType_ : null; }
      set {
        responseType_ = value;
        responseTypeCase_ = value == null ? ResponseTypeOneofCase.None : ResponseTypeOneofCase.ReadAcc;
      }
    }

    /// <summary>Field number for the "read_gyro" field.</summary>
    public const int ReadGyroFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mpsim.ResponseReadGyro ReadGyro {
      get { return responseTypeCase_ == ResponseTypeOneofCase.ReadGyro ? (global::Mpsim.ResponseReadGyro) responseType_ : null; }
      set {
        responseType_ = value;
        responseTypeCase_ = value == null ? ResponseTypeOneofCase.None : ResponseTypeOneofCase.ReadGyro;
      }
    }

    /// <summary>Field number for the "write_motor" field.</summary>
    public const int WriteMotorFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Mpsim.ResponseWriteMotor WriteMotor {
      get { return responseTypeCase_ == ResponseTypeOneofCase.WriteMotor ? (global::Mpsim.ResponseWriteMotor) responseType_ : null; }
      set {
        responseType_ = value;
        responseTypeCase_ = value == null ? ResponseTypeOneofCase.None : ResponseTypeOneofCase.WriteMotor;
      }
    }

    private object responseType_;
    /// <summary>Enum of possible cases for the "response_type" oneof.</summary>
    public enum ResponseTypeOneofCase {
      None = 0,
      ReadAcc = 2,
      ReadGyro = 3,
      WriteMotor = 4,
    }
    private ResponseTypeOneofCase responseTypeCase_ = ResponseTypeOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ResponseTypeOneofCase ResponseTypeCase {
      get { return responseTypeCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearResponseType() {
      responseTypeCase_ = ResponseTypeOneofCase.None;
      responseType_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Response);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Response other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Success != other.Success) return false;
      if (!object.Equals(ReadAcc, other.ReadAcc)) return false;
      if (!object.Equals(ReadGyro, other.ReadGyro)) return false;
      if (!object.Equals(WriteMotor, other.WriteMotor)) return false;
      if (ResponseTypeCase != other.ResponseTypeCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Success != false) hash ^= Success.GetHashCode();
      if (responseTypeCase_ == ResponseTypeOneofCase.ReadAcc) hash ^= ReadAcc.GetHashCode();
      if (responseTypeCase_ == ResponseTypeOneofCase.ReadGyro) hash ^= ReadGyro.GetHashCode();
      if (responseTypeCase_ == ResponseTypeOneofCase.WriteMotor) hash ^= WriteMotor.GetHashCode();
      hash ^= (int) responseTypeCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Success != false) {
        output.WriteRawTag(8);
        output.WriteBool(Success);
      }
      if (responseTypeCase_ == ResponseTypeOneofCase.ReadAcc) {
        output.WriteRawTag(18);
        output.WriteMessage(ReadAcc);
      }
      if (responseTypeCase_ == ResponseTypeOneofCase.ReadGyro) {
        output.WriteRawTag(26);
        output.WriteMessage(ReadGyro);
      }
      if (responseTypeCase_ == ResponseTypeOneofCase.WriteMotor) {
        output.WriteRawTag(34);
        output.WriteMessage(WriteMotor);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Success != false) {
        output.WriteRawTag(8);
        output.WriteBool(Success);
      }
      if (responseTypeCase_ == ResponseTypeOneofCase.ReadAcc) {
        output.WriteRawTag(18);
        output.WriteMessage(ReadAcc);
      }
      if (responseTypeCase_ == ResponseTypeOneofCase.ReadGyro) {
        output.WriteRawTag(26);
        output.WriteMessage(ReadGyro);
      }
      if (responseTypeCase_ == ResponseTypeOneofCase.WriteMotor) {
        output.WriteRawTag(34);
        output.WriteMessage(WriteMotor);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Success != false) {
        size += 1 + 1;
      }
      if (responseTypeCase_ == ResponseTypeOneofCase.ReadAcc) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ReadAcc);
      }
      if (responseTypeCase_ == ResponseTypeOneofCase.ReadGyro) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ReadGyro);
      }
      if (responseTypeCase_ == ResponseTypeOneofCase.WriteMotor) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(WriteMotor);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Response other) {
      if (other == null) {
        return;
      }
      if (other.Success != false) {
        Success = other.Success;
      }
      switch (other.ResponseTypeCase) {
        case ResponseTypeOneofCase.ReadAcc:
          if (ReadAcc == null) {
            ReadAcc = new global::Mpsim.ResponseReadAcc();
          }
          ReadAcc.MergeFrom(other.ReadAcc);
          break;
        case ResponseTypeOneofCase.ReadGyro:
          if (ReadGyro == null) {
            ReadGyro = new global::Mpsim.ResponseReadGyro();
          }
          ReadGyro.MergeFrom(other.ReadGyro);
          break;
        case ResponseTypeOneofCase.WriteMotor:
          if (WriteMotor == null) {
            WriteMotor = new global::Mpsim.ResponseWriteMotor();
          }
          WriteMotor.MergeFrom(other.WriteMotor);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Success = input.ReadBool();
            break;
          }
          case 18: {
            global::Mpsim.ResponseReadAcc subBuilder = new global::Mpsim.ResponseReadAcc();
            if (responseTypeCase_ == ResponseTypeOneofCase.ReadAcc) {
              subBuilder.MergeFrom(ReadAcc);
            }
            input.ReadMessage(subBuilder);
            ReadAcc = subBuilder;
            break;
          }
          case 26: {
            global::Mpsim.ResponseReadGyro subBuilder = new global::Mpsim.ResponseReadGyro();
            if (responseTypeCase_ == ResponseTypeOneofCase.ReadGyro) {
              subBuilder.MergeFrom(ReadGyro);
            }
            input.ReadMessage(subBuilder);
            ReadGyro = subBuilder;
            break;
          }
          case 34: {
            global::Mpsim.ResponseWriteMotor subBuilder = new global::Mpsim.ResponseWriteMotor();
            if (responseTypeCase_ == ResponseTypeOneofCase.WriteMotor) {
              subBuilder.MergeFrom(WriteMotor);
            }
            input.ReadMessage(subBuilder);
            WriteMotor = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Success = input.ReadBool();
            break;
          }
          case 18: {
            global::Mpsim.ResponseReadAcc subBuilder = new global::Mpsim.ResponseReadAcc();
            if (responseTypeCase_ == ResponseTypeOneofCase.ReadAcc) {
              subBuilder.MergeFrom(ReadAcc);
            }
            input.ReadMessage(subBuilder);
            ReadAcc = subBuilder;
            break;
          }
          case 26: {
            global::Mpsim.ResponseReadGyro subBuilder = new global::Mpsim.ResponseReadGyro();
            if (responseTypeCase_ == ResponseTypeOneofCase.ReadGyro) {
              subBuilder.MergeFrom(ReadGyro);
            }
            input.ReadMessage(subBuilder);
            ReadGyro = subBuilder;
            break;
          }
          case 34: {
            global::Mpsim.ResponseWriteMotor subBuilder = new global::Mpsim.ResponseWriteMotor();
            if (responseTypeCase_ == ResponseTypeOneofCase.WriteMotor) {
              subBuilder.MergeFrom(WriteMotor);
            }
            input.ReadMessage(subBuilder);
            WriteMotor = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
